### ISSUE TITLE
Inconsistency in look-up table conversion in cooling_cuda.cu

### ISSUE THREAD

**Issue by brantr** [cholla-hydro/cholla#304]
I am trying to reconcile various offline versions of the code base. One difference I noticed between a code base @bvillasen shared on June 15, 2023 and the current code main code base is in `src/cooling/cooling_cuda.cu` around line 344 in the `main` branch:
  
```
  // remap coordinates for texture
  log_T = (log_T - 1.0)*10;
  log_n = (log_n + 6.0)*10;
```
  
 This appears in Bruno's version as
 
 ```
  // remap coordinates for texture
  log_T = (log_T - 1.0)/8.1;
  log_n = (log_n + 6.0)/12.1;
```
This seems different!  Any idea or recollection of what may have happened here? @bvillasen @evaneschneider

**Comment by bvillasen** [comment]
seems like it was by @alwinm in this commit: https://github.com/cholla-hydro/cholla/commit/d79ed0b7e33d3d53f8a0d6d3dbd53acd8e1290fe

**Comment by evaneschneider** [comment]
Right, @alwinm rewrote the texture mapping since the old version with texture references no longer compiles for modern versions of cuda (which require texture objects). That said, I didn't think @bvillasen  actually used any of the code in that source file? Or at least not the Cloudy cooling function?

**Comment by bvillasen** [comment]
That's right, I don't use the cuda_cooling module. I think that the discrepancy is because those changes were pushed to the main branch without passing through the CAAR branch. @brantr The code that I sent you is the same as the CAAR branch which includes the most up-to-date version of cosmology. It seems like the CAAR branch has not been combined with the main branch in a while... perhaps that would be a good idea

**Comment by alwinm** [comment]
Just to help explain what happened, in the past the old version with texture references assumed normalized texture coordinates, which require passing in values from 0.0 to 1.0. Hence, the division by 8.1 and 12.1. 

In the new version, I took out the normalization because I didn't want CUDA applying 8-bit interpolation, which was leading to surprises (errors) of O(1e-2) when I was testing the cooling module. We now directly access exact values from the table and do our own bilinear interpolation. Since input coordinates are not normalized between 0.0 and 1.0 anymore, they are instead table coordinates, hence the multiplication by 10 since we have 10 values per decade in the table.

**Comment by evaneschneider** [comment]
To clarify, last August I pulled the last of the CAAR (as in, for the CAAR project) changes into dev (and main). I believe Bruno submitted one additional PR last fall to the CAAR branch with updates to cosmology and chemistry, which we (the Pitt developers) have not touched. We have been doing our development work on dev, since that is the branch where we now have automated regression testing. I have not had the person-power to have someone pull Bruno's final CAAR PR into dev since October, since we don't have any experience on our side running the cosmology code.

I believe this issue can be closed since your initial question is resolved, @brantr?

**Comment by brantr** [comment]
OK, that's fine. Closing.

Yes, Bruno, I am integrating src/fft/ into Nick's RT fork.
