### ISSUE TITLE
Updating wiki with documentation of example problems

### ISSUE THREAD

**Issue by evazlimen** [cholla-hydro/cholla#324]
Hi,
I have a version of the cholla wiki with the example problems documented: https://github.com/evazlimen/cholla-fork/wiki. This is also the same as the example-writeups branch of the main cholla wiki. 
How should I be handling tests that aren't performing as expected (very few, 1D Creasey shock, 1D Noh, 2D KH Resolution Independent, 2D Rayleigh-Taylor, 2&3D Disk, spherical collapse, and Zeldovich pancake. Most of these issues are with the initial conditions)? Right now they are excluded from the wiki but I can easily throw them in. The documentation of all tests, working and non-working is still available on https://github.com/evazlimen/cholla-example-tests.

**Comment by brantr** [comment]
Great, perhaps @evaneschneider can review the wiki and decide whether to include just the working tests?

**Comment by evaneschneider** [comment]
Yes, sorry for my slow response on this, I'm at a conference this week. I think it would be helpful to include the results of all the tests, even the ones that aren't working currently, so that we have a snapshot saved of what the performance was at this point in time. For the ones that aren't working, you could add a disclaimer at the top that says "not working" or something like that.

**Comment by bvillasen** [comment]
Just a comment... for the spherical collapse test GRAVITY needed to be turned on, otherwise there will be no evolution as the sphere collapses under its own self-gravity. 
For the Zeldoivich test, GRAVITY and COSMOLY need to be on. I just noticed that the Zeldovich test requires an initial conditions file. I'll see if I have it somewhere, if not maybe that test can be removed

**Comment by evaneschneider** [comment]
Just wanted to say that I am fine with all of this going into the main Cholla wiki! And I think @evazlimen  you should have write permissions to update it at your leisure. I also think the plots are great, and if you wanted to submit a PR to add your plotting scripts to the python_scripts directory, that would be super helpful!

**Comment by evazlimen** [comment]
Great, thanks. I'll start putting them in
